hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}_without_exp
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "zscl_.json"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."

batch_size: 128
initial_increment: 10  
increment: ${initial_increment}
scenario: "class"
dataset: "cifar100"

num_workers: 16
train_batch_size: 100
epochs: 15
lr: 0.001
fp16: false
seed: 2
margin: 0.2
milestones: [4,10]
beta: 2
mix_bias: 0.6
threshold: 0.65
shrinkage: True
